name: Email to Telegram Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests pytz

      - name: Run script
        env:
          EMAIL_ACCOUNT: ${{ secrets.EMAIL_ACCOUNT }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          IMAP_SERVER: ${{ secrets.IMAP_SERVER }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_GROUP_ID: ${{ secrets.TELEGRAM_GROUP_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_TOPIC_ID }}
        run: python email_to_telegram.py
